### ISSUE TITLE
JS Best Practices

### ISSUE THREAD

**Issue by codedit334** [codedit334/ToDo_List_Webpack#8]
- In file UI.js:
  - In line 111: instead of `validate(e)` use `validate(event)`.
  - Same for file completed.js.

**Comment by DilsherB** [comment]
1. in UI.js replace line 15-16 by `return(todoItems || [])`
2. in UI.js replace line 22-25 by `const filterTodoItems = todoItems.filter((e) => e.completed === false);`

**Comment by codedit334** [comment]
> 1. in UI.js replace line 15-16 by `return(todoItems || [])`:

Good call, I will make the change

> 2. in UI.js replace line 22-25 by `const filterTodoItems = todoItems.filter((e) => e.completed === false);`:

As for this the `filterByID()` is used do delete singular items aswell as checked items therefore I'm afraid I can't make this change...

Thanks @DilsherB.
